---
galaxy_info:
  author: Shane Breatnach
  company: Glicsoft
  description:
  min_ansible_version: 1.9
  license: BSD
  github_branch: master
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  - name: Debian
    versions:
    - all
  galaxy_tags:
    - desktop
dependencies:
  - common